services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: delicego
      POSTGRES_USER: delicego
      POSTGRES_PASSWORD: delicego
    ports:
      - "5433:5432"
    volumes:
      - delicego_postgres_donnees:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@delicego.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  delicego_postgres_donnees:
